import Navigation from "@/components/Navigation";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navigation />
        <main className="w-max-screen-md flex flex-col justify-center items-center bg-slate-100 h-screen">
          {children}
        </main>
        <footer className="bg-blue-600 w-full">
          <div className="flex flex-col justify-center items-center">
            Footer
          </div>
        </footer>
      </body>
    </html>
  );
}
